import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'
import { Authenticator } from '@aws-amplify/ui-react';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material';
import theme from './theme';
import { Amplify } from 'aws-amplify';
import '@aws-amplify/ui-react/styles.css';

// In a real deployment, this file is generated by Amplify
// import outputs from '../amplify_outputs.json';
// Amplify.configure(outputs);

// MOCK CONFIGURATION FOR DEMO PURPOSES IF OUTPUTS MISSING
try {
    // @ts-ignore
    import('../amplify_outputs.json').then(module => {
        Amplify.configure(module.default);
    }).catch(() => {
        console.warn("amplify_outputs.json not found. Backend features will not work until deployed.");
    });
} catch (e) {
    console.warn("Dynamic import failed");
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Authenticator>
        <App />
      </Authenticator>
    </ThemeProvider>
  </React.StrictMode>,
)
